version: '2'
services:
  mariadb:
    container_name: mariadb
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../../data/website/db:/bitnami/mariadb 
    networks:
      - rails

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/rails:5
    container_name: myapp
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=my_app_development
      - RAILS_ENV=production
    depends_on:
      - mariadb
    volumes:
      - .:/app
      - ../../data/website/gems:/opt/bitnami/ruby/lib/ruby/gems
      - ../website.secrets.yml:/app/config/secrets.yml
    networks:
      - rails

  locapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/rails:5
    container_name: myapp
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=my_app_development
    ports:
      - '127.0.0.1:3001:3000'
    depends_on:
      - mariadb
    volumes:
      - .:/app
    networks:
      - rails
        
  nginx:
    container_name: nginx
    image: 'bitnami/nginx:1.16'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./config/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
      - ../../data/website/certs:/certs
    networks:
      - rails
    depends_on:
      - myapp
          
networks:
  rails:
